### ISSUE TITLE
Github.io site is wrong

### ISSUE THREAD

**Issue by coretl** [bluesky/python3-pip-skeleton#5]
Should be `blueskyproject.io`, not `blueskyproject.github.io`

**Comment by coretl** [comment]
E.g. https://github.com/bluesky/python3-pip-skeleton/blame/main/docs/developer/how-to/update-tools.rst#L16

**Comment by evvaaaa** [comment]
Will also change in the skeleton adoption branch and squash

**Comment by coretl** [comment]
No need to squash, put on a branch in this skeleton, do a PR, this will do a rebase onto main, then do a git pull python3-pip-skeleton from event model and it should all work

**Comment by evvaaaa** [comment]
Ah I already squashed, never mind though, will still be able to git pull fine.
