### ISSUE TITLE
Publish docs to blueskyproject.io

### ISSUE THREAD

**Issue by evvaaaa** [bluesky/python3-pip-skeleton#7]
The skeleton repo docs should be added to blueskyproject.io.

**Comment by coretl** [comment]
I think if you turn on gh pages for this repo it will just appear at https://blueskyproject.io/python3-pip-skeleton

**Comment by evvaaaa** [comment]
Leaving this here so I remember when I deal with this:
"I saw there was a mention of blueskyproject.github.io. I think it should be either bluesky.github.io or blueskyproject.io (the former redirects to the latter one)."

**Comment by coretl** [comment]
gh pages is on, and serving. There are a few references to blueskyproject.github.io which need changing to blueskyproject.io. There is also a reference to https://blueskyproject.github.io/python3-pip-skeleton-cli in the README that needs changing to https://DiamondLightSource.github.io/python3-pip-skeleton-cli
